/*
 * MutationsReport.java
 *
 * Created on 16 janvier 2007, 18:37
 */

/**
 *
 * @author  cauchy
 */
import java.io.*;
import javax.swing.*;
import java.awt.*;
public class MutationsReport extends javax.swing.JFrame {
    
    String report;
    /** Creates new form MutationsReport */
    public MutationsReport(String s) {
        report=s;
        initComponents();
        jTextArea1.setRows(this.getNumRows());
        jTextArea1.setText(report);
        jTextArea1.setEditable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jTextArea1.setCaretPosition(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        jScrollPane1.setViewportView(jScrollBar1);

        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("SansSerif", 0, 11));
        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("SansSerif", 0, 11));
        jMenuItem1.setText("Save");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
        
        FileDialog myDialog = new FileDialog(this, "Save",java.awt.FileDialog.SAVE);
        myDialog.setTitle("Choose a File to Save");
        myDialog.show();
        
        //gets abstract path
        String fileName = myDialog.getFile();
        String directory = myDialog.getDirectory();
        
        try
                
            {
                //safeguard if no file chosen
                if(directory==null||fileName==null)
                {
                    throw new NullPointerException();
                }
                
                
                
                FileSaver newFile = new FileSaver(jTextArea1.getText(), directory, fileName);
                
                
            
            }
            
            
            catch(NullPointerException npe)
            {
            
            }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public int getNumRows()
    {
        int numRows=0;
        for(int i =0;i<report.length();i++)
        {
            if(report.charAt(i)=='\n')
            {
                numRows++;
            }
        }
            
        return numRows;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
