/*
 * VectorFrame.java
 *
 * Created on 11 janvier 2007, 14:59
 */
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;   
/**
 *
 * @author  cauchy
 */
public class proxyOptions extends javax.swing.JFrame {
    
    /** Creates new form VectorFrame */
    String proxyHost="";
    String proxyPort="";
    
    
    
    public proxyOptions() {
        initComponents();
        this.setVisible(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        
        
        
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public void centreFrame(JFrame frame)
    {
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension size = frame.getSize();
        screenSize.height = screenSize.height/2;
        screenSize.width = screenSize.width/2;
        size.height = size.height/2;
        size.width = size.width/2;
        int y = screenSize.height - size.height;
        int x = screenSize.width - size.width;
        frame.setLocation(x, y);

    }
    public void getOptions()
    {
        proxyHost = jTextField1.getText();
        proxyPort = jTextField2.getText();
        
    }
    
    public String returnProxyHost()
    {
        return proxyHost;
    }
    
    public String returnProxyPort()
    {
        return proxyPort;
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jLabel1.setText("Proxy Host");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 20);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jLabel2.setText("Proxy Port");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 50, 70, 20);

        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 20, 150, 19);

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);
        jButton1.setBounds(20, 90, 80, 24);

        jButton2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2);
        jButton2.setBounds(190, 90, 80, 24);

        jPanel1.add(jTextField2);
        jTextField2.setBounds(120, 50, 50, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 130);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        proxyHost="";
        proxyPort="";
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        this.getOptions();
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
}
