/*
 * VectorFrame.java
 *
 * Created on 11 janvier 2007, 14:59
 */
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;   
/**
 *
 * @author  cauchy
 */
public class VectorFrame extends javax.swing.JFrame {
    
    /** Creates new form VectorFrame */
    String vector;
    int start=0;
    boolean isSet=false;
    String[] result;
    boolean isProtein = false;
    
    
    public VectorFrame() {
        initComponents();
        this.setSize(500, 200);
        this.setTitle("Please enter vector DNA Sequence and gap");
        this.setVisible(true);
        this.centreFrame(this);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.show();
        
        
    }
    
    public String[] returnResult()
    {
        return result;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public void centreFrame(JFrame frame)
    {
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension size = frame.getSize();
        screenSize.height = screenSize.height/2;
        screenSize.width = screenSize.width/2;
        size.height = size.height/2;
        size.width = size.width/2;
        int y = screenSize.height - size.height;
        int x = screenSize.width - size.width;
        frame.setLocation(x, y);

    }
    public void getVector()
    {
        
        vector=jTextField1.getText();
        if((vector.equals(""))||(vector.equals(null)))
        {
            this.getProteinVector();
        }
        else
        {
        result = new String[2];
        result[0]=vector;
        result[1]=Integer.toString(start);
        isSet=true;
        isProtein=false;
        }
    }
    
    public void getProteinVector()
    {
        vector=jTextField3.getText();
        result = new String[2];
        result[0]=vector;
        result[1]=Integer.toString(start);
        isSet=true;
        isProtein=true;
    }
    public boolean isProtein()
    {
        return isProtein;
    }
    
    
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jLabel1.setText("DNA Sequence");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 20);

        jSlider1.setMajorTickSpacing(1);
        jSlider1.setValue(1);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jPanel1.add(jSlider1);
        jSlider1.setBounds(170, 90, 290, 20);

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jLabel2.setText("Distance to ORF");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 110, 20);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jTextField2.setText("0");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(100, 90, 30, 20);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 20, 290, 19);

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);
        jButton1.setBounds(170, 130, 80, 23);

        jButton2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2);
        jButton2.setBounds(300, 130, 80, 23);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 11));
        jLabel3.setText("bp");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 90, 20, 20);

        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });

        jPanel1.add(jTextField3);
        jTextField3.setBounds(170, 60, 290, 19);

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jLabel4.setText("A.A. Sequence");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 60, 90, 20);

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11));
        jLabel5.setText("or");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 40, 20, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
// TODO add your handling code here:
        jLabel3.setText("bp");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
// TODO add your handling code here:
        jLabel3.setText("aa");
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        result=null;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        this.getVector();
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
// TODO add your handling code here:
        start=jSlider1.getValue();
        jTextField2.setText(Integer.toString(start));
        this.update(this.getGraphics());
    }//GEN-LAST:event_jSlider1StateChanged
    
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    
}
